### ISSUE TITLE
Where is PhysX3.4.0

### ISSUE THREAD

**Issue by zhengchuanzhe** [NVIDIAGameWorks/PhysX-3.4#112]
I want to use vs2017 to build  PhysX3.4.0, but I can't find it

**Comment by AlesBorovicka** [comment]
You mean the solution files for VS2017? They are here:
https://github.com/NVIDIAGameWorks/PhysX-3.4/blob/master/PhysX_3.4/Source/compiler/vc15win64/PhysX.sln

**Comment by zhengchuanzhe** [comment]
> You mean the solution files for VS2017? They are here:
> https://github.com/NVIDIAGameWorks/PhysX-3.4/blob/master/PhysX_3.4/Source/compiler/vc15win64/PhysX.sln

This is 3.4.2,But I want 3.4.0

**Comment by AlesBorovicka** [comment]
It was not supported during 3.4.0 release because of a compiler bug in VC15, the support was added later. Feel free to upgrade the VC14 projects to VC15.

**Comment by zhengchuanzhe** [comment]
> It was not supported during 3.4.0 release because of a compiler bug in VC15, the support was added later. Feel free to upgrade the VC14 projects to VC15.

I build v3.4.0-rc-2  using vs2017,but the rebuilding failed.

**Comment by zhengchuanzhe** [comment]
I want 3.4.0，where can I download it?

**Comment by sschirm** [comment]
3.4.0 is v3.4.0-rc-2 as far as I can tell. The tag is misleading as it was not updated. But the correct change is "PhysX 3.4, APEX 1.4 final release @21757769" 7840347c32755e94a807f978f1cbb558717ac8cf
