### ISSUE TITLE
Buffer overrun in Aggregate::computeBounds

### ISSUE THREAD

**Issue by wankotank** [NVIDIAGameWorks/PhysX-3.4#116]
In Aggregate::computeBounds, Accessing PxBounds3 elements with V4LoadU causes buffer overrun.

**Comment by Pierre-Terdiman** [comment]
Do you have a repro? This should not happen because we explicitly allocate one more entry than strictly necessary in the bounds manager:

https://github.com/NVIDIAGameWorks/PhysX-3.4/blob/master/PhysX_3.4/Source/LowLevelAABB/include/BpSimpleAABBManager.h#L130

**Comment by wankotank** [comment]
Hi Pierre-Terdiman.

I'm sorry!
It was occurred in a title using an old version. It does not occur in the latest version.
