### ISSUE TITLE
Hot to setOwnerClient for Controller actors

### ISSUE THREAD

**Issue by drashnane** [NVIDIAGameWorks/PhysX-3.4#117]
Hi ,
I'm trying multi client, and  I find that PxControllerManager::createController adds actor into the scene without calling setOwnerClient

Is there any way to call setOwnerClient before controller adds actor into the scene?

**Comment by Pierre-Terdiman** [comment]
There is currently no way to do that.

One thing that might work is simply removing the actor from the scene, calling setOwnerClient, and re-adding the actor to the scene.

**Comment by PierreTerdiman** [comment]
FWIW I added a client ID parameter for controllers, which will appear in the 5.0 API. For previous versions the previously suggested workaround should work.
