### ISSUE TITLE
Missing IOS and OSX project files

### ISSUE THREAD

**Issue by sunwtGitHub** [NVIDIAGameWorks/PhysX-3.4#128]
Why APEX1.4 does not have ios and osx project files? Now I have to create my own Xcode project to compile Apex.

**Comment by sschirm** [comment]
Sorry, we don't support APEX1.4 beyond making it available anymore. It is up do you to port it to more platforms as needed.

**Comment by sunwtGitHub** [comment]
Thank you for your prompt reply. we're still using Apex for some reason and require it to work on various platforms.if there is already have ios and osx project files, it can help us save a lot of development time.
