### ISSUE TITLE
array subscript below bounds

### ISSUE THREAD

**Issue by dschmid2** [NVIDIAGameWorks/PhysX-3.4#16]
./../../GeomUtils/src/mesh/GuBV4.cpp: In member function ‘void physx::Gu::SourceMesh::remapTopology(const physx::PxU32*)’:
./../../GeomUtils/src/mesh/GuBV4.cpp:84: error: array subscript is below array bounds [-Warray-bounds]

found on: 
gcc (SUSE Linux) 4.3.2 [gcc-4_3-branch revision 141291]

**Comment by amoravanszky** [comment]
Closing until we get a clarification on this.
