### ISSUE TITLE
Suggestion: Rename "PhysX_3.4" folder to "PhysX"

### ISSUE THREAD

**Issue by GregSlazinski** [NVIDIAGameWorks/PhysX-3.4#47]
In my opinion keeping version names in folders is generally a bad idea.
I'm an engine developer working on integrating PhysX into my engine.
I need to have several hard coded paths to the physx folder:
-compiler include directories for headers
-linker include directories/files for compiler libraries
-my own toolchain for physx compilation

So when you release a future update, PhysX 3.5 or another, I would have to set it all up again.
My current workaround is I already rename the "PhysX_3.4" to "PhysX" by myself in the builder toolchain application to avoid this problem in the future. But I would prefer to have consistency between my toolchain and what's present in the official SDK.

Thank you

**Comment by amoravanszky** [comment]
This is a good point.  We will fix this for version 4, coming later this month.
