### ISSUE TITLE
Problem with BasicFS and IOFX modules.

### ISSUE THREAD

**Issue by Gletschr** [NVIDIAGameWorks/PhysX-3.4#59]
Errors appeared after upgrade to APEX 1.4 + PhysX 3.4 (on APEX 1.3.1 + PhysX 3.3.1 all works fine).

**Problem in IOFX module:**
When I create 1 emitter on a physical scene, APEX requests the creation of 3 sprite buffers and 3 render resources (previously (on APEX 1.3 and PhysX 3.3.1), 1 emitter requested 1 sprite buffer and 1 render resource).

**Problem in BasicFS module:**
The VortexFSActor incorrectly rotates the particles along Z axis (the rotation on the X and Y axes is correct).

**Comment by amoravanszky** [comment]
Thanks but we will not be releasing further patches to the deprecated APEX SDK.
