### ISSUE TITLE
Compile Failed/Multiple Errors

### ISSUE THREAD

**Issue by parsarahimi** [NVIDIAGameWorks/PhysX-3.4#71]
I am using Visual Studio 2017 professional and I used the solution in \PhysX_3.4\Source\compiler\vc15win64 since that was the latest version (so it is logically the one that is most likely to be compiled successfully).
Can you edit the description and make it easier for everyone to understand what they have to do to compile the SDK? The documentation in https://docs.nvidia.com/gameworks/content/gameworkslibrary/physx/guide/Manual/Index.html is also very poorly written and vague...

**Comment by amoravanszky** [comment]
Closing until more feedback.
