### ISSUE TITLE
Missing APEX Particle solutions

### ISSUE THREAD

**Issue by Greavesy1899** [NVIDIAGameWorks/PhysX-3.4#89]
I cannot find the projects for the particle module, which im guessing should be in every folder in **PhysX-3.4/APEX_1.4/compiler/**.

I tried to build and run the APEX 1.4 samples but had no luck due to missing the particles module.

**Comment by sabdulajees** [comment]
Which version of Visual Studio do compile with? We only provide the particles and turbulence modules as pre-built binaries.

**Comment by Greavesy1899** [comment]
I compiled with Visual Studio 2015.

**Comment by sabdulajees** [comment]
Please note that GPU support as well as particles will be disabled when the APEX SDK is rebuilt. You can have it enabled by not rebuilding the ApexFramework dll or replacing it with the pre-built one.
