### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by jamesdolan** [NVIDIAGameWorks/PhysX-3.4#92]
Awesome news on the new license! Mind if you add a LICENSE or License.txt file at the root for clarity purposes?

**Comment by amoravanszky** [comment]
Given that the readme.md file is automatically displayed I thought it was actually clearer this way.  If you can clarify the benefit of having a separate license file we can do it that way for the upcoming 4.0 release.

Ultimately the depot includes third party external code (like glew headers) that is not covered by our copyright so if you want to be really picky you can't let a single top level file imply the status of the whole depot anyway, and you need to look at the per-source file boilerplates.  It would be cleaner to reuse external code through e.g. package managers which we want to do for future releases but I am not excited about doing a bunch of refactor like that for past releases.
