### ISSUE TITLE
platform transplant 

### ISSUE THREAD

**Issue by ka1nong** [NVIDIAGameWorks/PhysX-3.4#98]
ask a platform transplant problem, I found that the PhyX library has a PX_INTEL_FAMILY macro, this macro allows the inter-architecture CPU to use the SSE2 instruction, PX_ARM_FAMILY is also related to some optimizations. Does the application packaged platform cause problems if it is inconsistent with the actual run platform cpu structure?

**Comment by AlesBorovicka** [comment]
Hi,
 I am not sure I understand the question. These macros are defined in PxShared/include/foundation/PxPreprocessor.h 
They are defined based on the HW/compiler defines.

Ales
